import type { McpServerFileEntry } from "./config.ts";

export type McpRegistryCategory =
	| "Development & Testing"
	| "Project Management & Documentation"
	| "Payments & Commerce"
	| "Design & Media"
	| "Infrastructure & DevOps"
	| "Additional Stdio Servers"
	| "Remote Servers";

export interface McpCatalogServer {
	name: string;
	title: string;
	category: McpRegistryCategory;
	description: string;
	detail: string;
	config: McpServerFileEntry;
	requiredEnv: string[];
	disabledReason?: string;
}

const GENERAL_MCP_SERVERS: readonly McpCatalogServer[] = [
	remoteServer({
		name: "sentry",
		title: "Sentry",
		category: "Development & Testing",
		description: "Monitor errors, debug production issues",
		url: "https://mcp.sentry.dev/mcp",
	}),
	remoteServer({
		name: "hugging-face",
		title: "Hugging Face",
		category: "Development & Testing",
		description: "Access Hugging Face Hub and Gradio AI applications",
		url: "https://huggingface.co/mcp",
	}),
	stdioServer({
		name: "socket",
		title: "Socket",
		category: "Development & Testing",
		description: "Security analysis for dependencies",
		command: "npx",
		args: ["-y", "@socketsecurity/mcp"],
		env: { SOCKET_API_TOKEN: envRef("SOCKET_API_KEY") },
		requiredEnv: ["SOCKET_API_KEY"],
	}),
	stdioServer({
		name: "playwright",
		title: "Playwright",
		category: "Development & Testing",
		description: "End-to-end browser testing",
		command: "npx",
		args: ["-y", "@playwright/mcp@latest"],
	}),
	stdioServer({
		name: "context7",
		title: "Context7",
		category: "Development & Testing",
		description: "Fetch up-to-date package documentation and examples",
		command: "npx",
		args: ["-y", "@upstash/context7-mcp@latest"],
	}),
	remoteServer({
		name: "notion",
		title: "Notion",
		category: "Project Management & Documentation",
		description: "Read docs, update pages, manage tasks",
		url: "https://mcp.notion.com/mcp",
	}),
	remoteServer({
		name: "linear",
		title: "Linear",
		category: "Project Management & Documentation",
		description: "Issue tracking and project management",
		url: "https://mcp.linear.app/mcp",
	}),
	remoteServer({
		name: "intercom",
		title: "Intercom",
		category: "Project Management & Documentation",
		description: "Access customer conversations and tickets",
		url: "https://mcp.intercom.com/mcp",
	}),
	stdioServer({
		name: "monday",
		title: "Monday",
		category: "Project Management & Documentation",
		description: "Manage monday.com boards and items",
		command: "npx",
		args: ["-y", "@mondaydotcomorg/monday-api-mcp"],
		requiredEnv: ["MONDAY_API_KEY"],
	}),
	remoteServer({
		name: "stripe",
		title: "Stripe",
		category: "Payments & Commerce",
		description: "Payment processing and subscriptions",
		url: "https://mcp.stripe.com",
	}),
	stdioServer({
		name: "paypal",
		title: "PayPal",
		category: "Payments & Commerce",
		description: "PayPal commerce and payment processing",
		command: "npx",
		args: ["-y", "@paypal/mcp", "--tools=all"],
		env: {
			PAYPAL_ACCESS_TOKEN: envRef("PAYPAL_ACCESS_TOKEN"),
			PAYPAL_ENVIRONMENT: envRef("PAYPAL_ENVIRONMENT:-SANDBOX"),
		},
		requiredEnv: ["PAYPAL_ACCESS_TOKEN"],
	}),
	remoteServer({
		name: "figma",
		title: "Figma",
		category: "Design & Media",
		description: "Remote server only supports approved Figma MCP clients",
		url: "https://mcp.figma.com/mcp",
		disabledReason:
			"Figma remote MCP only works with approved clients. Use manual setup: figma-desktop=http://127.0.0.1:3845/mcp after enabling the Figma desktop MCP server.",
	}),
	remoteServer({
		name: "canva",
		title: "Canva",
		category: "Design & Media",
		description: "Browse, summarize, and generate Canva designs",
		url: "https://mcp.canva.com/mcp",
	}),
	stdioServer({
		name: "twelvelabs",
		title: "TwelveLabs",
		category: "Design & Media",
		description: "Video analysis, search, and AI-powered insights",
		command: "npx",
		args: ["-y", "--package", "twelvelabs-mcp", "twelvelabs-mcp-stdio"],
		requiredEnv: ["TWELVE_LABS_API_KEY"],
	}),
	stdioServer({
		name: "netlify",
		title: "Netlify",
		category: "Infrastructure & DevOps",
		description: "Create, deploy, and manage websites",
		command: "npx",
		args: ["-y", "@netlify/mcp"],
		requiredEnv: ["NETLIFY_AUTH_TOKEN"],
	}),
	remoteServer({
		name: "vercel",
		title: "Vercel",
		category: "Infrastructure & DevOps",
		description: "Manage projects, deployments, and logs",
		url: "https://mcp.vercel.com",
	}),
	stdioServer({
		name: "airtable",
		title: "Airtable",
		category: "Additional Stdio Servers",
		description: "Read/write records, manage bases and tables",
		command: "npx",
		args: ["-y", "airtable-mcp-server"],
		requiredEnv: ["AIRTABLE_API_KEY"],
	}),
	stdioServer({
		name: "clickup",
		title: "ClickUp",
		category: "Additional Stdio Servers",
		description: "Task management and project tracking",
		command: "npx",
		args: ["-y", "@taazkareem/clickup-mcp-server"],
		requiredEnv: ["CLICKUP_API_KEY"],
	}),
	stdioServer({
		name: "hubspot",
		title: "HubSpot",
		category: "Additional Stdio Servers",
		description: "Access and manage CRM data",
		command: "npx",
		args: ["-y", "@hubspot/mcp-server"],
		requiredEnv: ["HUBSPOT_ACCESS_TOKEN"],
	}),
	stdioServer({
		name: "mongodb",
		title: "MongoDB",
		category: "Additional Stdio Servers",
		description: "Database management",
		command: "npx",
		args: ["-y", "mongodb-mcp-server"],
		env: { MDB_MCP_CONNECTION_STRING: envRef("MONGODB_URI") },
		requiredEnv: ["MONGODB_URI"],
	}),
	remoteServer({
		name: "supabase",
		title: "Supabase",
		category: "Additional Stdio Servers",
		description: "Create and manage Supabase projects",
		url: "https://mcp.supabase.com/mcp",
	}),
];

const CLAUDE_REMOTE_MCP_SERVERS: readonly McpCatalogServer[] = [
	remoteServer({
		name: "ticket-tailor",
		title: "Ticket Tailor",
		category: "Remote Servers",
		description: "Event platform for managing tickets, orders & more",
		url: "https://mcp.tickettailor.ai/mcp",
	}),
	remoteServer({
		name: "blockscout",
		title: "Blockscout",
		category: "Remote Servers",
		description: "Access and analyze blockchain data",
		url: "https://mcp.blockscout.com/mcp",
	}),
	remoteServer({
		name: "close",
		title: "Close",
		category: "Remote Servers",
		description:
			"Connect Claude to Close CRM to securely access and act on your sales data",
		url: "https://mcp.close.com/mcp",
	}),
	remoteServer({
		name: "cloudflare-developer-platform",
		title: "Cloudflare Developer Platform",
		category: "Remote Servers",
		description: "Build applications with compute, storage, and AI",
		url: "https://bindings.mcp.cloudflare.com/mcp",
	}),
	remoteServer({
		name: "egnyte",
		title: "Egnyte",
		category: "Remote Servers",
		description: "Securely access and analyze Egnyte content",
		url: "https://mcp-server.egnyte.com/mcp",
	}),
	remoteServer({
		name: "guru",
		title: "Guru",
		category: "Remote Servers",
		description: "Search and interact with your company knowledge",
		url: "https://mcp.api.getguru.com/mcp",
	}),
	remoteServer({
		name: "jotform",
		title: "Jotform",
		category: "Remote Servers",
		description: "Create forms & analyze submissions inside Claude",
		url: "https://mcp.jotform.com/mcp-app",
	}),
	remoteServer({
		name: "wix",
		title: "Wix",
		category: "Remote Servers",
		description: "Manage and build sites and apps on Wix",
		url: "https://mcp.wix.com/mcp",
	}),
	remoteServer({
		name: "coupler-io",
		title: "Coupler.io",
		category: "Remote Servers",
		description: "Access business data from hundreds of sources",
		url: "https://mcp.coupler.io/mcp/",
	}),
	remoteServer({
		name: "dice",
		title: "Dice",
		category: "Remote Servers",
		description: "Find active tech jobs on Dice",
		url: "https://mcp.dice.com/mcp",
	}),
	remoteServer({
		name: "miro",
		title: "Miro",
		category: "Remote Servers",
		description: "Access and create new content on Miro boards",
		url: "https://mcp.miro.com/",
	}),
	remoteServer({
		name: "aiwyn-tax-formerly-column-tax",
		title: "Aiwyn Tax (formerly Column Tax)",
		category: "Remote Servers",
		description: "Estimate your federal & state taxes with Aiwyn's tax engine",
		url: "https://mcp.columnapi.com/mcp",
	}),
	remoteServer({
		name: "circleback",
		title: "Circleback",
		category: "Remote Servers",
		description: "Search and access context from meetings",
		url: "https://app.circleback.ai/api/mcp",
	}),
	remoteServer({
		name: "clarify",
		title: "Clarify",
		category: "Remote Servers",
		description: "Query your CRM. Create records. Ask anything.",
		url: "https://api.clarify.ai/mcp",
	}),
	remoteServer({
		name: "clarity-ai",
		title: "Clarity AI",
		category: "Remote Servers",
		description: "Simulate fund classifications under proposed SFDR 2.0",
		url: "https://clarity-sfdr20-mcp.pro.clarity.ai/mcp",
	}),
	remoteServer({
		name: "day-ai",
		title: "Day AI",
		category: "Remote Servers",
		description: "Know everything about your prospects & customers with CRMx",
		url: "https://day.ai/api/mcp",
	}),
	remoteServer({
		name: "icd-10-codes",
		title: "ICD-10 Codes",
		category: "Remote Servers",
		description: "Access ICD-10-CM and ICD-10-PCS code sets",
		url: "https://hcls.mcp.claude.com/icd10_codes/mcp",
	}),
	remoteServer({
		name: "devrev",
		title: "DevRev",
		category: "Remote Servers",
		description: "Search and update your company's knowledge graph",
		url: "https://api.devrev.ai/mcp/v1",
	}),
	remoteServer({
		name: "exa",
		title: "Exa",
		category: "Remote Servers",
		description: "Web Search + Code Docs Search",
		url: "https://mcp.exa.ai/mcp",
	}),
	remoteServer({
		name: "fathom",
		title: "Fathom",
		category: "Remote Servers",
		description: "Your meetings, now part of every Claude conversation",
		url: "https://api.fathom.ai/mcp",
	}),
	remoteServer({
		name: "fireflies",
		title: "Fireflies",
		category: "Remote Servers",
		description: "Analyze and generate insights from meeting transcripts",
		url: "https://api.fireflies.ai/mcp",
	}),
	remoteServer({
		name: "fiscal-ai",
		title: "Fiscal.ai",
		category: "Remote Servers",
		description: "Clean Public Equity Fundamental Data",
		url: "https://api.fiscal.ai/mcp/sse",
	}),
	remoteServer({
		name: "granola",
		title: "Granola",
		category: "Remote Servers",
		description: "The AI notepad for meetings",
		url: "https://mcp.granola.ai/mcp",
	}),
	remoteServer({
		name: "harmonic",
		title: "Harmonic",
		category: "Remote Servers",
		description: "Discover, research, and enrich companies and people",
		url: "https://mcp.api.harmonic.ai",
	}),
	remoteServer({
		name: "klarity",
		title: "Klarity",
		category: "Remote Servers",
		description: "Explore your org's processes",
		url: "https://architect-v2-api.klarity.ai/mcp",
	}),
	remoteServer({
		name: "krisp",
		title: "Krisp",
		category: "Remote Servers",
		description: "Add your meetings context via transcripts and notes",
		url: "https://mcp.krisp.ai/mcp",
	}),
	remoteServer({
		name: "lawve-ai",
		title: "Lawve AI",
		category: "Remote Servers",
		description: "Discover expert-written skills for legal work",
		url: "https://mcp.lawve.ai/mcp",
	}),
	remoteServer({
		name: "lorikeet",
		title: "Lorikeet",
		category: "Remote Servers",
		description: "A universal concierge for complex businesses",
		url: "https://mcp.lorikeetcx.ai",
	}),
	remoteServer({
		name: "lunarcrush",
		title: "LunarCrush",
		category: "Remote Servers",
		description: "Add real-time social media data to your searches",
		url: "https://lunarcrush.ai/mcp",
	}),
	remoteServer({
		name: "mem",
		title: "Mem",
		category: "Remote Servers",
		description: "The AI notebook for everything on your mind",
		url: "https://mcp.mem.ai/mcp",
	}),
	remoteServer({
		name: "metaview",
		title: "Metaview",
		category: "Remote Servers",
		description: "The AI platform for recruiting.",
		url: "https://mcp.metaview.ai/mcp",
	}),
	remoteServer({
		name: "otter-ai",
		title: "Otter.ai",
		category: "Remote Servers",
		description: "Unlock your meeting intelligence",
		url: "https://mcp.otter.ai/mcp",
	}),
	remoteServer({
		name: "peec-ai",
		title: "Peec AI",
		category: "Remote Servers",
		description: "Analyze your brand's visibility across LLMs",
		url: "https://api.peec.ai/mcp",
	}),
	remoteServer({
		name: "read-ai",
		title: "Read AI",
		category: "Remote Servers",
		description: "Bring your meetings into Claude",
		url: "https://api.read.ai/mcp",
	}),
	remoteServer({
		name: "scholar-gateway",
		title: "Scholar Gateway",
		category: "Remote Servers",
		description: "Enhance responses with scholarly research and citations",
		url: "https://connector.scholargateway.ai/mcp",
	}),
	remoteServer({
		name: "scite",
		title: "Scite",
		category: "Remote Servers",
		description: "Evidence-based answers grounded in research",
		url: "https://api.scite.ai/mcp",
	}),
	remoteServer({
		name: "sprouts-data-intelligence",
		title: "Sprouts Data Intelligence",
		category: "Remote Servers",
		description: "From query to qualified lead in seconds.",
		url: "https://sprouts-mcp-server.kartikay-dhar.workers.dev",
	}),
	remoteServer({
		name: "sybill",
		title: "Sybill",
		category: "Remote Servers",
		description: "Ask AI about your sales calls, deals & pipeline",
		url: "https://mcp.sybill.ai/mcp",
	}),
	remoteServer({
		name: "vibe-prospecting",
		title: "Vibe Prospecting",
		category: "Remote Servers",
		description: "Find company & contact data",
		url: "https://vibeprospecting.explorium.ai/mcp",
	}),
	remoteServer({
		name: "windsor-ai",
		title: "Windsor.ai",
		category: "Remote Servers",
		description:
			"Connect Meta Ads, Google Ads, TikTok Ads, LinkedIn Ads + 320 more",
		url: "https://mcp.windsor.ai",
	}),
	remoteServer({
		name: "era-context",
		title: "Era Context",
		category: "Remote Servers",
		description: "Manage your personal finances using Claude",
		url: "https://context.era.app",
	}),
	remoteServer({
		name: "fellow-ai",
		title: "Fellow.ai",
		category: "Remote Servers",
		description: "Chat with your meetings to uncover actionable insights",
		url: "https://fellow.app/mcp",
	}),
	remoteServer({
		name: "gamma",
		title: "Gamma",
		category: "Remote Servers",
		description: "Create presentations, docs, socials, and sites with AI",
		url: "https://mcp.gamma.app/mcp",
	}),
	remoteServer({
		name: "lucid",
		title: "Lucid",
		category: "Remote Servers",
		description: "Ideate, diagram, and align teams",
		url: "https://mcp.lucid.app/mcp",
	}),
	remoteServer({
		name: "thoughtspot-spotter",
		title: "ThoughtSpot Spotter",
		category: "Remote Servers",
		description: "Your AI data analyst, from question to trusted insights",
		url: "https://agent.thoughtspot.app/mcp?api-version=latest",
	}),
	remoteServer({
		name: "aws-marketplace",
		title: "AWS Marketplace",
		category: "Remote Servers",
		description: "Discover, evaluate, and buy solutions for the cloud",
		url: "https://marketplace-mcp.us-east-1.api.aws/mcp",
	}),
	remoteServer({
		name: "synthesize-bio",
		title: "Synthesize Bio",
		category: "Remote Servers",
		description: "Generate gene expression from a virtual human",
		url: "https://app.synthesize.bio/api/mcp",
	}),
	remoteServer({
		name: "kindora-funder-discovery",
		title: "Kindora Funder Discovery",
		category: "Remote Servers",
		description: "Find funders who support causes like yours",
		url: "https://kindora-mcp.azurewebsites.net/mcp/",
	}),
	remoteServer({
		name: "omni-analytics",
		title: "Omni Analytics",
		category: "Remote Servers",
		description:
			"Query your data using natural language through Omni's semantic model",
		url: "https://callbacks.omniapp.co/callback/mcp",
	}),
	remoteServer({
		name: "send",
		title: "Send",
		category: "Remote Servers",
		description: "Create shareable documents, one-pagers, and decks",
		url: "https://www.send.co/mcp",
	}),
	remoteServer({
		name: "shapes",
		title: "Shapes",
		category: "Remote Servers",
		description: "Analyse your live people data, right in Claude",
		url: "https://mcp.shapes.co/mcp",
	}),
	remoteServer({
		name: "topcounsel-by-the-l-suite",
		title: "TopCounsel by The L Suite",
		category: "Remote Servers",
		description: "Outside Counsel recommendations from Inhouse Counsel",
		url: "https://api.techgc.co/api/mcp/topcounsel",
	}),
	remoteServer({
		name: "adobe-experience-manager",
		title: "Adobe Experience Manager",
		category: "Remote Servers",
		description: "Manage your Adobe Experience Manager content",
		url: "https://mcp.adobeaemcloud.com/adobe/mcp/aem",
	}),
	remoteServer({
		name: "ahrefs",
		title: "Ahrefs",
		category: "Remote Servers",
		description: "SEO & AI search analytics",
		url: "https://api.ahrefs.com/mcp/mcp",
	}),
	remoteServer({
		name: "airops",
		title: "AirOps",
		category: "Remote Servers",
		description: "Craft content that wins AI search",
		url: "https://app.airops.com/mcp",
	}),
	remoteServer({
		name: "airwallex-developer",
		title: "Airwallex Developer",
		category: "Remote Servers",
		description: "Integrate with the Airwallex Platform using Claude",
		url: "https://mcp-demo.airwallex.com/developer",
	}),
	remoteServer({
		name: "alltrails",
		title: "AllTrails",
		category: "Remote Servers",
		description: "Find your next hike",
		url: "https://www.alltrails.com/mcp",
	}),
	remoteServer({
		name: "attio",
		title: "Attio",
		category: "Remote Servers",
		description: "Search, manage, and update your Attio CRM from Claude",
		url: "https://mcp.attio.com/mcp",
	}),
	remoteServer({
		name: "autodesk-product-help",
		title: "Autodesk Product Help",
		category: "Remote Servers",
		description: "Securely access Autodesk's help documentation",
		url: "https://developer.api.autodesk.com/knowledge/public/v1/mcp",
	}),
	remoteServer({
		name: "base44",
		title: "Base44",
		category: "Remote Servers",
		description: "Build and manage Base44 apps",
		url: "https://app.base44.com/mcp",
	}),
	remoteServer({
		name: "biorender",
		title: "BioRender",
		category: "Remote Servers",
		description: "Search for and use scientific templates and icons",
		url: "https://mcp.services.biorender.com/mcp",
	}),
	remoteServer({
		name: "bitly",
		title: "Bitly",
		category: "Remote Servers",
		description: "Shorten links, generate QR Codes, and track performance",
		url: "https://api-ssl.bitly.com/v4/mcp",
	}),
	remoteServer({
		name: "mt-newswires",
		title: "MT Newswires",
		category: "Remote Servers",
		description: "Trusted real-time global financial news provider",
		url: "https://vast-mcp.blueskyapi.com/mcp",
	}),
	remoteServer({
		name: "box",
		title: "Box",
		category: "Remote Servers",
		description: "Search, edit and get insights on your Box content",
		url: "https://mcp.box.com",
		disabledReason:
			"Box MCP requires admin-issued client credentials from the Box Admin Console; dynamic client registration is not supported.",
	}),
	remoteServer({
		name: "brex",
		title: "Brex",
		category: "Remote Servers",
		description: "Intelligent finance automation",
		url: "https://api.brex.com/mcp",
	}),
	remoteServer({
		name: "orion-by-gravity",
		title: "Orion by Gravity",
		category: "Remote Servers",
		description: "Get insights from your autonomous AI analyst",
		url: "https://g.runorion.com/mcp",
	}),
	remoteServer({
		name: "calendly",
		title: "Calendly",
		category: "Remote Servers",
		description: "Manage event types, availability, and bookings.",
		url: "https://mcp.calendly.com",
	}),
	remoteServer({
		name: "carta",
		title: "Carta",
		category: "Remote Servers",
		description: "The connected ERP for private capital",
		url: "https://mcp.app.carta.com/mcp",
	}),
	remoteServer({
		name: "cb-insights",
		title: "CB Insights",
		category: "Remote Servers",
		description: "Predictive intelligence on private companies",
		url: "https://mcp.cbinsights.com",
	}),
	remoteServer({
		name: "cdata-connect-ai",
		title: "CData Connect AI",
		category: "Remote Servers",
		description: "Managed MCP platform for 350 sources",
		url: "https://mcp.cloud.cdata.com/mcp",
	}),
	remoteServer({
		name: "microsoft-365",
		title: "Microsoft 365",
		category: "Remote Servers",
		description:
			"Access your company's SharePoint, OneDrive, Outlook, and Teams directly in Claude",
		url: "https://microsoft365.mcp.claude.com/mcp",
	}),
	remoteServer({
		name: "pubmed",
		title: "PubMed",
		category: "Remote Servers",
		description: "Search biomedical literature from PubMed",
		url: "https://pubmed.mcp.claude.com/mcp",
	}),
	remoteServer({
		name: "clay",
		title: "Clay",
		category: "Remote Servers",
		description: "Find prospects. Research accounts. Personalize outreach",
		url: "https://api.clay.com/v3/mcp",
	}),
	remoteServer({
		name: "clerk",
		title: "Clerk",
		category: "Remote Servers",
		description: "Add authentication, organizations, and billing",
		url: "https://mcp.clerk.com/mcp",
	}),
	remoteServer({
		name: "imanage-work",
		title: "iManage Work",
		category: "Remote Servers",
		description: "Governed knowledge. AI ready.",
		url: "https://cloudimanage.com/mcp/work",
	}),
	remoteServer({
		name: "cloudinary",
		title: "Cloudinary",
		category: "Remote Servers",
		description: "Manage, transform and deliver your images & videos",
		url: "https://asset-management.mcp.cloudinary.com/sse",
	}),
	remoteServer({
		name: "coindesk",
		title: "CoinDesk",
		category: "Remote Servers",
		description: "Access Live & Historical Crypto Data, Indices",
		url: "https://mcp.coindesk.com/mcp",
	}),
	remoteServer({
		name: "consensus",
		title: "Consensus",
		category: "Remote Servers",
		description: "Explore scientific research",
		url: "https://mcp.consensus.app/mcp",
	}),
	remoteServer({
		name: "aurora",
		title: "Aurora",
		category: "Remote Servers",
		description: "Search your Consilio matters, docs, and more.",
		url: "https://mcp.ai.consilio.com",
	}),
	remoteServer({
		name: "contentsquare",
		title: "Contentsquare",
		category: "Remote Servers",
		description: "Experience analytics platform for digital businesses",
		url: "https://api.contentsquare.com/mcp",
	}),
	remoteServer({
		name: "courtlistener",
		title: "CourtListener",
		category: "Remote Servers",
		description: "Legal research across millions of court records",
		url: "https://mcp.courtlistener.com/",
	}),
	remoteServer({
		name: "courtroom5",
		title: "Courtroom5",
		category: "Remote Servers",
		description: "Civil legal guidance for self-represented litigants",
		url: "https://mcp.courtroom5.com/v1",
	}),
	remoteServer({
		name: "intuit-credit-karma",
		title: "Intuit Credit Karma",
		category: "Remote Servers",
		description: "Credit score factors & insights",
		url: "https://anthropic.mcp.creditkarma.com/mcp",
	}),
	remoteServer({
		name: "crossbeam",
		title: "Crossbeam",
		category: "Remote Servers",
		description: "Explore partner data and ecosystem insights in Claude",
		url: "https://mcp.crossbeam.com",
	}),
	remoteServer({
		name: "crypto-com",
		title: "Crypto.com",
		category: "Remote Servers",
		description: "Real time prices, orders, charts, and more for crypto",
		url: "https://mcp.crypto.com/market-data/mcp",
	}),
	remoteServer({
		name: "daloopa",
		title: "Daloopa",
		category: "Remote Servers",
		description: "Financial fundamental data and KPIs with hyperlinks",
		url: "https://mcp.daloopa.com/server/mcp",
	}),
	remoteServer({
		name: "datasite",
		title: "Datasite",
		category: "Remote Servers",
		description: "Manage your M&A data room from Claude",
		url: "https://mcp.global.datasite.com/mcp",
	}),
	remoteServer({
		name: "definely",
		title: "Definely",
		category: "Remote Servers",
		description: "Structured contract review tools for legal teams",
		url: "https://mcp.app.definely.com",
	}),
	remoteServer({
		name: "descript",
		title: "Descript",
		category: "Remote Servers",
		description: "Import, edit, or create video with prompts",
		url: "https://api.descript.com/v2/mcp/claude",
	}),
	remoteServer({
		name: "descrybe-legal-engine",
		title: "Descrybe Legal Engine",
		category: "Remote Servers",
		description: "Ground your work in clean, structured U.S. primary law",
		url: "https://mcp.descrybe.com/mcp",
	}),
	remoteServer({
		name: "digits",
		title: "Digits",
		category: "Remote Servers",
		description: "Track and analyze your finances with Digits",
		url: "https://api.digits.com/mcp",
	}),
	remoteServer({
		name: "dovetail",
		title: "Dovetail",
		category: "Remote Servers",
		description:
			"Turn scattered feedback into decisions grounded in customer evidence",
		url: "https://dovetail.com/api/mcp",
	}),
	remoteServer({
		name: "enterpret",
		title: "Enterpret",
		category: "Remote Servers",
		description: "Get answers from unified feedback of your customers.",
		url: "https://wisdom-api.enterpret.com/server/mcp",
	}),
	remoteServer({
		name: "euler",
		title: "Euler",
		category: "Remote Servers",
		description: "Chat and manage your entire partner program.",
		url: "https://mcp.eulerapp.com/mcp",
	}),
	remoteServer({
		name: "fever-event-discovery",
		title: "Fever Event Discovery",
		category: "Remote Servers",
		description: "Discover live entertainment events worldwide",
		url: "https://data-search.apigw.feverup.com/mcp",
	}),
	remoteServer({
		name: "monte-carlo",
		title: "Monte Carlo",
		category: "Remote Servers",
		description: "Data & AI observability",
		url: "https://mcp.getmontecarlo.com/mcp",
	}),
	remoteServer({
		name: "gocardless",
		title: "GoCardless",
		category: "Remote Servers",
		description: "Build GoCardless payment API integrations",
		url: "https://mcp.gocardless.com",
	}),
	remoteServer({
		name: "godaddy",
		title: "GoDaddy",
		category: "Remote Servers",
		description: "Search domains and check availability",
		url: "https://api.godaddy.com/v1/domains/mcp",
	}),
	remoteServer({
		name: "goodnotes",
		title: "Goodnotes",
		category: "Remote Servers",
		description: "Turn AI insights into documents",
		url: "https://claude-mcp-api.ml.goodnotes.com/mcp",
	}),
	remoteServer({
		name: "google-cloud-bigquery",
		title: "Google Cloud BigQuery",
		category: "Remote Servers",
		description: "BigQuery: Advanced analytical insights for agents",
		url: "https://bigquery.googleapis.com/mcp",
		disabledReason:
			"Google MCP servers require a pre-registered OAuth client and do not support dynamic client registration. Static OAuth client support is planned.",
	}),
	remoteServer({
		name: "google-compute-engine",
		title: "Google Compute Engine",
		category: "Remote Servers",
		description: "MCP server for Google Compute Engine",
		url: "https://compute.googleapis.com/mcp",
		disabledReason:
			"Google MCP servers require a pre-registered OAuth client and do not support dynamic client registration. Static OAuth client support is planned.",
	}),
	remoteServer({
		name: "google-calendar",
		title: "Google Calendar",
		category: "Remote Servers",
		description: "Manage your schedule and coordinate meetings effortlessly",
		url: "https://calendarmcp.googleapis.com/mcp/v1",
		disabledReason:
			"Google MCP servers require a pre-registered OAuth client and do not support dynamic client registration. Static OAuth client support is planned.",
	}),
	remoteServer({
		name: "google-drive",
		title: "Google Drive",
		category: "Remote Servers",
		description: "Search, read, and upload files instantly",
		url: "https://drivemcp.googleapis.com/mcp/v1",
		disabledReason:
			"Google MCP servers require a pre-registered OAuth client and do not support dynamic client registration. Static OAuth client support is planned.",
	}),
	remoteServer({
		name: "gmail",
		title: "Gmail",
		category: "Remote Servers",
		description: "Draft replies, summarize threads, & search your inbox",
		url: "https://gmailmcp.googleapis.com/mcp/v1",
		disabledReason:
			"Google MCP servers require a pre-registered OAuth client and do not support dynamic client registration. Static OAuth client support is planned.",
	}),
	remoteServer({
		name: "govtribe",
		title: "GovTribe",
		category: "Remote Servers",
		description: "Search government procurement & spending data",
		url: "https://govtribe.com/mcp",
	}),
	remoteServer({
		name: "grain",
		title: "Grain",
		category: "Remote Servers",
		description: "Put your meetings to work",
		url: "https://api.grain.com/_/mcp",
	}),
	remoteServer({
		name: "granted",
		title: "Granted",
		category: "Remote Servers",
		description: "Discover every grant opportunity in existence.",
		url: "https://grantedai.com/api/mcp/mcp",
	}),
	remoteServer({
		name: "guidepoint",
		title: "Guidepoint",
		category: "Remote Servers",
		description: "Real-time access to trusted expert knowledge",
		url: "https://clapi.guidepoint.io/mcp-server/v1/mcp",
	}),
	remoteServer({
		name: "gusto",
		title: "Gusto",
		category: "Remote Servers",
		description: "Query and analyze your Gusto data",
		url: "https://mcp.api.gusto.com/anthropic",
	}),
	remoteServer({
		name: "phoenix-by-hg-insights",
		title: "Phoenix by HG Insights",
		category: "Remote Servers",
		description: "AI-powered B2B data intelligence & analytics",
		url: "https://phoenix.hginsights.com/api/ai/mcp",
	}),
	remoteServer({
		name: "ibisworld",
		title: "IBISWorld",
		category: "Remote Servers",
		description: "Financials, risk data and analysis on 50,000 industries",
		url: "https://mcp.ibisworld.com",
	}),
	remoteServer({
		name: "interactive-brokers-ibkr",
		title: "Interactive Brokers (IBKR)",
		category: "Remote Servers",
		description: "Trade, invest, analyze, and manage global markets",
		url: "https://api.ibkr.com/v1/api/mcp",
	}),
	remoteServer({
		name: "ifttt",
		title: "IFTTT",
		category: "Remote Servers",
		description: "Connect, control, and automate 1,000+ apps with IFTTT",
		url: "https://ifttt.com/mcp",
	}),
	remoteServer({
		name: "medidata",
		title: "Medidata",
		category: "Remote Servers",
		description: "Clinical trial software and site ranking tools",
		url: "https://mcp.imedidata.com/mcp",
	}),
	remoteServer({
		name: "indeed",
		title: "Indeed",
		category: "Remote Servers",
		description: "Search for jobs on Indeed",
		url: "https://mcp.indeed.com/claude/mcp",
	}),
	remoteServer({
		name: "jentic",
		title: "Jentic",
		category: "Remote Servers",
		description: "One connection to access all your tools securely",
		url: "https://api.jentic.com/mcp",
	}),
	remoteServer({
		name: "playmcp",
		title: "PlayMCP",
		category: "Remote Servers",
		description: "Connect and use PlayMCP servers in your toolbox",
		url: "https://playmcp.kakao.com/mcp",
	}),
	remoteServer({
		name: "sandp-global",
		title: "S&P Global",
		category: "Remote Servers",
		description: "Query a range of S&P Global datasets",
		url: "https://kfinance.kensho.com/integrations/mcp",
	}),
	remoteServer({
		name: "ketryx",
		title: "Ketryx",
		category: "Remote Servers",
		description: "Search and explore regulated software lifecycle data",
		url: "https://app.ketryx.com/api/mcp",
	}),
	remoteServer({
		name: "kiwi-com",
		title: "Kiwi.com",
		category: "Remote Servers",
		description: "Search flights in Claude",
		url: "https://mcp.kiwi.com",
	}),
	remoteServer({
		name: "klaviyo",
		title: "Klaviyo",
		category: "Remote Servers",
		description: "Report, strategize & create with real-time Klaviyo data",
		url: "https://mcp.klaviyo.com/mcp?include-mcp-app=true",
	}),
	remoteServer({
		name: "legal-data-hunter",
		title: "Legal Data Hunter",
		category: "Remote Servers",
		description: "Search 23M+ legal docs in 160+ jurisdictions.",
		url: "https://legaldatahunter.com/mcp",
	}),
	remoteServer({
		name: "lilt",
		title: "LILT",
		category: "Remote Servers",
		description: "High-quality translation with human verification",
		url: "https://mcp.lilt.com/mcp",
	}),
	remoteServer({
		name: "local-falcon",
		title: "Local Falcon",
		category: "Remote Servers",
		description: "AI visibility and local search intelligence platform",
		url: "https://mcp.localfalcon.com",
	}),
	remoteServer({
		name: "lseg",
		title: "LSEG",
		category: "Remote Servers",
		description:
			"Access best in class data & analytics across a broad spectrum of asset classes.",
		url: "https://api.analytics.lseg.com/lfa/mcp/server-cl",
	}),
	remoteServer({
		name: "lumin",
		title: "Lumin",
		category: "Remote Servers",
		description:
			"Manage documents, send signature requests, and convert Markdown to PDF",
		url: "https://mcp.luminpdf.com/mcp",
	}),
	remoteServer({
		name: "lusha",
		title: "Lusha",
		category: "Remote Servers",
		description: "Find and enrich B2B contacts and companies",
		url: "https://mcp.lusha.com/mcp/claude",
	}),
	remoteServer({
		name: "magic-patterns",
		title: "Magic Patterns",
		category: "Remote Servers",
		description: "Discuss and iterate on Magic Patterns designs",
		url: "https://mcp.magicpatterns.com/mcp",
	}),
	remoteServer({
		name: "mailerlite",
		title: "MailerLite",
		category: "Remote Servers",
		description: "Turn Claude into your email marketing assistant",
		url: "https://mcp.mailerlite.com/mcp",
	}),
	remoteServer({
		name: "make",
		title: "Make",
		category: "Remote Servers",
		description: "Run Make scenarios and manage your Make account",
		url: "https://mcp.make.com",
	}),
	remoteServer({
		name: "malwarebytes",
		title: "Malwarebytes",
		category: "Remote Servers",
		description: "Check links, phones, and emails for scams",
		url: "https://scamguard.malwarebytes.com/claude/mcp",
	}),
	remoteServer({
		name: "mercury",
		title: "Mercury",
		category: "Remote Servers",
		description: "Search, analyze and understand your finances on Mercury",
		url: "https://mcp.mercury.com/mcp",
	}),
	remoteServer({
		name: "microsoft-learn",
		title: "Microsoft Learn",
		category: "Remote Servers",
		description: "Search trusted Microsoft docs to power your development",
		url: "https://learn.microsoft.com/api/mcp",
	}),
	remoteServer({
		name: "mintlify",
		title: "Mintlify",
		category: "Remote Servers",
		description: "Search, read, and edit your documentation",
		url: "https://mcp.mintlify.com",
	}),
	remoteServer({
		name: "mixpanel",
		title: "Mixpanel",
		category: "Remote Servers",
		description: "Analyze, query, and manage your Mixpanel data",
		url: "https://mcp.mixpanel.com/mcp",
	}),
	remoteServer({
		name: "moody-s",
		title: "Moody's",
		category: "Remote Servers",
		description: "Risk insights, analytics, and decision intelligence",
		url: "https://api.moodys.com/genai-ready-data/m1/mcp",
	}),
	remoteServer({
		name: "morningstar",
		title: "Morningstar",
		category: "Remote Servers",
		description: "Up-to-date investment and market insights",
		url: "https://mcp.morningstar.com/mcp",
	}),
	remoteServer({
		name: "motherduck",
		title: "MotherDuck",
		category: "Remote Servers",
		description: "Get answers from your data",
		url: "https://api.motherduck.com/mcp",
	}),
	remoteServer({
		name: "motion-creative-analytics",
		title: "Motion Creative Analytics",
		category: "Remote Servers",
		description: "Analyze your Meta ad creative & competitor ad libraries",
		url: "https://projects.motionapp.com/mcp",
	}),
	remoteServer({
		name: "msci",
		title: "MSCI",
		category: "Remote Servers",
		description: "Turn data into insight",
		url: "https://mcp.msci.com/mcp/v1.0/mcp",
	}),
	remoteServer({
		name: "pagerduty",
		title: "PagerDuty",
		category: "Remote Servers",
		description: "Manage incidents, services and on-call schedules",
		url: "https://mcp.pagerduty.com/mcp",
		disabledReason:
			"PagerDuty MCP requires a pre-registered OAuth app or User API Token; dynamic client registration is not supported.",
	}),
	remoteServer({
		name: "pandadoc",
		title: "PandaDoc",
		category: "Remote Servers",
		description: "Create, send, sign and track documents",
		url: "https://mcp.pandadoc.com/v1/mcp",
	}),
	remoteServer({
		name: "pitchbook-premium",
		title: "PitchBook Premium",
		category: "Remote Servers",
		description: "PitchBook data, embedded in the way you work.",
		url: "https://premium.mcp.pitchbook.com/mcp",
	}),
	remoteServer({
		name: "polar-analytics",
		title: "Polar Analytics",
		category: "Remote Servers",
		description: "Bring all your data in one place & connect it to Claude",
		url: "https://api.polaranalytics.com/mcp",
	}),
	remoteServer({
		name: "postman",
		title: "Postman",
		category: "Remote Servers",
		description: "Give API context to your coding agents",
		url: "https://mcp.postman.com/minimal",
	}),
	remoteServer({
		name: "privacy-com",
		title: "Privacy.com",
		category: "Remote Servers",
		description: "Manage virtual cards and track your spending patterns",
		url: "https://mcp.privacy.com",
	}),
	remoteServer({
		name: "quartr",
		title: "Quartr",
		category: "Remote Servers",
		description: "Financial data and AI infrastructure for company research.",
		url: "https://mcp.quartr.com/mcp",
	}),
	remoteServer({
		name: "quo",
		title: "Quo",
		category: "Remote Servers",
		description: "Surface call insights and missed opportunities",
		url: "https://mcp.quo.com/mcp",
	}),
	remoteServer({
		name: "ramp",
		title: "Ramp",
		category: "Remote Servers",
		description: "Search, access, and analyze your Ramp financial data",
		url: "https://ramp-mcp-remote.ramp.com/mcp",
	}),
	remoteServer({
		name: "ramp-data",
		title: "Ramp Data",
		category: "Remote Servers",
		description: "Search and analyze Ramp spend across 50,000+ businesses",
		url: "https://mcp.ramp.com/ramp-data/anthropic/mcp",
	}),
	remoteServer({
		name: "razorpay",
		title: "Razorpay",
		category: "Remote Servers",
		description: "Turn Claude into your Razorpay Dashboard Assistant",
		url: "https://mcp.razorpay.com/mcp",
	}),
	remoteServer({
		name: "rillet",
		title: "Rillet",
		category: "Remote Servers",
		description: "Query your live GL and financials in plain English",
		url: "https://api.rillet.com/mcp",
	}),
	remoteServer({
		name: "semrush",
		title: "Semrush",
		category: "Remote Servers",
		description: "SEO, market data, and brand visibility insights",
		url: "https://mcp.semrush.com/claude/v1/mcp",
	}),
	remoteServer({
		name: "signnow",
		title: "SignNow",
		category: "Remote Servers",
		description: "Automate eSignature workflows directly from Claude",
		url: "https://mcp-server.signnow.com/mcp",
	}),
	remoteServer({
		name: "similarweb",
		title: "Similarweb",
		category: "Remote Servers",
		description: "Real time web, mobile app, and market data.",
		url: "https://mcp.similarweb.com",
	}),
	remoteServer({
		name: "trimble-sketchup",
		title: "Trimble SketchUp",
		category: "Remote Servers",
		description: "Create and iterate 3D models for use in SketchUp",
		url: "https://api.sketchup.com/mcp/v1/sketchup/mcp",
	}),
	remoteServer({
		name: "slack",
		title: "Slack",
		category: "Remote Servers",
		description: "Send messages, create canvases, and fetch Slack data",
		url: "https://mcp.slack.com/mcp",
		disabledReason:
			"Slack MCP requires client credentials from an internal or Marketplace-listed Slack app; dynamic client registration is not supported.",
	}),
	remoteServer({
		name: "splice",
		title: "Splice",
		category: "Remote Servers",
		description: "Search Splice's sounds catalog, build stacks & more!",
		url: "https://mcp.splice.com/mcp",
	}),
	remoteServer({
		name: "adisinsight",
		title: "AdisInsight",
		category: "Remote Servers",
		description: "Pharmaceutical drug & clinical trial intelligence",
		url: "https://adisinsight-mcp.springer.com/mcp",
	}),
	remoteServer({
		name: "order-by-cash-app",
		title: "Order by Cash App",
		category: "Remote Servers",
		description: "Discover local food spots and order with a conversation",
		url: "https://connect.squareup.com/v2/mcp/cash-app",
	}),
	remoteServer({
		name: "square",
		title: "Square",
		category: "Remote Servers",
		description: "Search and manage transaction, merchant, and payment data",
		url: "https://mcp.squareup.com/sse",
	}),
	remoteServer({
		name: "superhuman-mail",
		title: "Superhuman Mail",
		category: "Remote Servers",
		description: "The most productive email app ever, for Gmail & Outlook",
		url: "https://mcp.mail.superhuman.com/mcp",
	}),
	remoteServer({
		name: "supermetrics-marketing-analytics",
		title: "Supermetrics Marketing Analytics",
		category: "Remote Servers",
		description: "Google Ads, Facebook Ads & 200+ marketing platforms",
		url: "https://mcp.supermetrics.com/mcp",
	}),
	remoteServer({
		name: "surveymonkey",
		title: "SurveyMonkey",
		category: "Remote Servers",
		description: "Design surveys, collect responses, and analyze results",
		url: "https://mcp.surveymonkey.com/mcp",
	}),
	remoteServer({
		name: "taskrabbit-booking-assistance",
		title: "Taskrabbit Booking Assistance",
		category: "Remote Servers",
		description: "Find & book local Taskrabbit services near you",
		url: "https://mcp.taskrabbit.com/mcp",
	}),
	remoteServer({
		name: "tavily",
		title: "Tavily",
		category: "Remote Servers",
		description: "Connect your AI agents to the web",
		url: "https://mcp.tavily.com/mcp",
	}),
	remoteServer({
		name: "third-bridge",
		title: "Third Bridge",
		category: "Remote Servers",
		description: "Expert-led enhanced insights",
		url: "https://ai.thirdbridge.com/mcp/sse",
	}),
	remoteServer({
		name: "cocounsel-legal",
		title: "CoCounsel Legal",
		category: "Remote Servers",
		description: "Thomson Reuters CoCounsel Legal, in Claude",
		url: "https://legal-mcp.thomsonreuters.com/mcp",
	}),
	remoteServer({
		name: "tldraw",
		title: "tldraw",
		category: "Remote Servers",
		description: "Let Claude sketch, draw, and diagram with you",
		url: "https://tldraw-mcp-app.tldraw.workers.dev/mcp",
	}),
	remoteServer({
		name: "tripadvisor",
		title: "Tripadvisor",
		category: "Remote Servers",
		description: "Find your perfect hotel based on Tripadvisor reviews",
		url: "https://production.ai-mcp-extensibility-prd.tamg.cloud/ogMvjY4De1G7CiHanMOAgddl/mcp",
	}),
	remoteServer({
		name: "turkish-airlines",
		title: "Turkish Airlines",
		category: "Remote Servers",
		description: "Search flights, plan trips, and manage bookings",
		url: "https://mcp-app.turkishtechlab.com/mcp",
	}),
	remoteServer({
		name: "twilio",
		title: "Twilio",
		category: "Remote Servers",
		description: "Build powerful communications and customer engagement",
		url: "https://mcp.twilio.com/docs",
	}),
	remoteServer({
		name: "udemy-business",
		title: "Udemy Business",
		category: "Remote Servers",
		description: "Search and explore skill-building resources",
		url: "https://api.udemy.com/mcp",
	}),
	remoteServer({
		name: "pylon",
		title: "Pylon",
		category: "Remote Servers",
		description: "Search and manage Pylon support issues",
		url: "https://mcp.usepylon.com/",
	}),
	remoteServer({
		name: "verisk-underwriting-intelligence",
		title: "Verisk Underwriting Intelligence",
		category: "Remote Servers",
		description: "Ask questions. Get underwriting insights from Verisk.",
		url: "https://gatewaymcp.verisk.com/underwriting/intelligencemcp/v1",
	}),
	remoteServer({
		name: "verisk-xactrestore",
		title: "Verisk XactRestore",
		category: "Remote Servers",
		description: "Natural-language estimating for XactRestore",
		url: "https://xactrestore-xactremodelserver-usw2-prod.propsol.io/mcp",
	}),
	remoteServer({
		name: "viator",
		title: "Viator",
		category: "Remote Servers",
		description: "Book travel experiences around the world",
		url: "https://exp-app-mcp.prod.ep.viator.com/mcp",
	}),
	remoteServer({
		name: "webflow",
		title: "Webflow",
		category: "Remote Servers",
		description: "Manage Webflow CMS, pages, assets and sites",
		url: "https://mcp.webflow.com/mcp",
	}),
	remoteServer({
		name: "wolfram",
		title: "Wolfram",
		category: "Remote Servers",
		description: "Inject precise, real-time computation and knowledge",
		url: "https://agenttools.wolfram.com/mcp",
	}),
	remoteServer({
		name: "wordpress-com",
		title: "WordPress.com",
		category: "Remote Servers",
		description: "Secure AI access to manage your WordPress.com sites",
		url: "https://public-api.wordpress.com/wpcom/v2/mcp/v1",
	}),
	remoteServer({
		name: "workable",
		title: "Workable",
		category: "Remote Servers",
		description: "Your AI assistant for Hiring and HR — inside Workable",
		url: "https://mcp.workable.com/mcp",
	}),
	remoteServer({
		name: "xero",
		title: "Xero",
		category: "Remote Servers",
		description: "Access your Xero financials from any conversation",
		url: "https://mcp.xero.com/mcp",
		disabledReason:
			"Xero MCP requires a pre-registered Xero OAuth app; dynamic client registration is not supported.",
	}),
	remoteServer({
		name: "zapier",
		title: "Zapier",
		category: "Remote Servers",
		description: "Automate workflows across thousands of apps via conversation",
		url: "https://mcp.zapier.com/api/v1/connect",
	}),
	remoteServer({
		name: "ziprecruiter",
		title: "ZipRecruiter",
		category: "Remote Servers",
		description: "Job search made easy",
		url: "https://api.ziprecruiter.com/mcp",
	}),
	remoteServer({
		name: "zoominfo",
		title: "ZoomInfo",
		category: "Remote Servers",
		description: "Enrich contacts & accounts with GTM intelligence",
		url: "https://mcp.zoominfo.com/mcp",
	}),
	remoteServer({
		name: "tango",
		title: "Tango",
		category: "Remote Servers",
		description: "Search for US Government Contracting Data",
		url: "https://govcon.dev/mcp",
	}),
	remoteServer({
		name: "jam",
		title: "Jam",
		category: "Remote Servers",
		description: "Record screen and collect automatic context for issues",
		url: "https://mcp.jam.dev/mcp",
	}),
	remoteServer({
		name: "stytch",
		title: "Stytch",
		category: "Remote Servers",
		description: "Manage your Stytch Project",
		url: "https://mcp.stytch.dev/mcp",
	}),
	remoteServer({
		name: "craft",
		title: "Craft",
		category: "Remote Servers",
		description: "Notes & second brain",
		url: "https://mcp.craft.do/my/mcp",
	}),
	remoteServer({
		name: "alma",
		title: "Alma",
		category: "Remote Servers",
		description: "Your nutrition data, inside every Claude conversation.",
		url: "https://mcp.alma.food",
	}),
	remoteServer({
		name: "mospi",
		title: "MoSPI",
		category: "Remote Servers",
		description: "India's official statistics via natural language",
		url: "https://mcp.mospi.gov.in/",
	}),
	remoteServer({
		name: "adobe-journey-optimizer",
		title: "Adobe Journey Optimizer",
		category: "Remote Servers",
		description: "Understand and troubleshoot your Journeys and Campaigns",
		url: "https://ajo-mcp.adobe.io/mcp",
	}),
	remoteServer({
		name: "adobe-marketing-agent",
		title: "Adobe Marketing Agent",
		category: "Remote Servers",
		description: "Marketing campaign and audience insights from Adobe",
		url: "https://aep-ai-ama.adobe.io/mcp",
	}),
	remoteServer({
		name: "common-room",
		title: "Common Room",
		category: "Remote Servers",
		description: "Your GTM Copilot",
		url: "https://mcp.commonroom.io/mcp",
	}),
	remoteServer({
		name: "eraser",
		title: "Eraser",
		category: "Remote Servers",
		description: "Generate, manage, and update Eraser diagrams and files",
		url: "https://app.eraser.io/api/mcp",
	}),
	remoteServer({
		name: "harness-io",
		title: "Harness.io",
		category: "Remote Servers",
		description: "Build, Ship and Secure your apps on Harness Platform",
		url: "https://mcp.harness.io/mcp",
	}),
	remoteServer({
		name: "honeycomb",
		title: "Honeycomb",
		category: "Remote Servers",
		description: "Query and explore observability data and SLOs",
		url: "https://mcp.honeycomb.io/mcp",
	}),
	remoteServer({
		name: "incident-io",
		title: "incident.io",
		category: "Remote Servers",
		description: "See and manage everything in incident.io",
		url: "https://mcp.incident.io/mcp",
	}),
	remoteServer({
		name: "sanity",
		title: "Sanity",
		category: "Remote Servers",
		description: "Create, query, and manage structured content in Sanity",
		url: "https://mcp.sanity.io",
	}),
	remoteServer({
		name: "tldv",
		title: "tldv",
		category: "Remote Servers",
		description: "Fetch Transcripts & Notes from Meet, Zoom & Teams",
		url: "https://mcp.tldv.io/mcp",
	}),
	remoteServer({
		name: "tropic",
		title: "Tropic",
		category: "Remote Servers",
		description: "Save money on Software + AI contracts",
		url: "https://app.tropicapp.io/mcp",
	}),
	remoteServer({
		name: "unthread",
		title: "Unthread",
		category: "Remote Servers",
		description: "Manage and automate your support tickets",
		url: "https://app.unthread.io/api/mcp",
	}),
	remoteServer({
		name: "zocks",
		title: "Zocks",
		category: "Remote Servers",
		description: "Analyze client conversations, patterns, and insights.",
		url: "https://mcp.zocks.io/v1/mcp",
	}),
	remoteServer({
		name: "todoist",
		title: "Todoist",
		category: "Remote Servers",
		description: "Search, complete, and manage your tasks in Todoist",
		url: "https://ai.todoist.net/mcp",
	}),
	remoteServer({
		name: "boardwise",
		title: "BoardWise",
		category: "Remote Servers",
		description: "Calm board-defense guidance for licensed pros.",
		url: "https://uakozrqrztgrgwoywxkx.supabase.co/functions/v1/mcp-server",
	}),
	remoteServer({
		name: "candid",
		title: "Candid",
		category: "Remote Servers",
		description: "Research nonprofits and funders using Candid's data",
		url: "https://mcp.candid.org/mcp",
	}),
	remoteServer({
		name: "open-targets",
		title: "Open Targets",
		category: "Remote Servers",
		description: "Drug target discovery and prioritisation platform",
		url: "https://mcp.platform.opentargets.org/mcp",
	}),
	remoteServer({
		name: "synapse-org",
		title: "Synapse.org",
		category: "Remote Servers",
		description: "Search and metadata tools for Synapse scientific data",
		url: "https://mcp.synapse.org/mcp",
	}),
	remoteServer({
		name: "chronograph",
		title: "Chronograph",
		category: "Remote Servers",
		description: "Interact with your Chronograph data directly in Claude",
		url: "https://ai.chronograph.pe/mcp",
	}),
	remoteServer({
		name: "zoom-for-claude",
		title: "Zoom for Claude",
		category: "Remote Servers",
		description: "Search, recap, and act on your Zoom meetings",
		url: "https://mcp.zoom.us/mcp/zoom/streamable",
		disabledReason:
			"Zoom MCP requires a pre-registered Zoom app; dynamic client registration is not supported.",
	}),
];

export const CURATED_MCP_SERVERS: readonly McpCatalogServer[] = [
	...GENERAL_MCP_SERVERS,
	...CLAUDE_REMOTE_MCP_SERVERS,
];

function remoteServer(input: {
	name: string;
	title: string;
	category: McpRegistryCategory;
	description: string;
	url: string;
	disabledReason?: string;
}): McpCatalogServer {
	return {
		name: input.name,
		title: input.title,
		category: input.category,
		description: input.description,
		detail: input.url,
		config: { type: "streamable-http", url: input.url },
		requiredEnv: [],
		...(input.disabledReason ? { disabledReason: input.disabledReason } : {}),
	};
}

function stdioServer(input: {
	name: string;
	title: string;
	category: McpRegistryCategory;
	description: string;
	command: string;
	args: string[];
	env?: Record<string, string>;
	requiredEnv?: string[];
}): McpCatalogServer {
	return {
		name: input.name,
		title: input.title,
		category: input.category,
		description: input.description,
		detail: [input.command, ...input.args].join(" "),
		config: {
			command: input.command,
			args: input.args,
			...(input.env ? { env: input.env } : envFromNames(input.requiredEnv)),
		},
		requiredEnv: input.requiredEnv ?? [],
	};
}

function envFromNames(
	names: readonly string[] | undefined,
): { env: Record<string, string> } | Record<string, never> {
	if (!names || names.length === 0) return {};
	return {
		env: Object.fromEntries(names.map((name) => [name, envRef(name)])),
	};
}

function envRef(name: string): string {
	return `\${${name}}`;
}
