export const DEFAULT_RLM_MAX_ITERATIONS = 20;
export const DEFAULT_RLM_MAX_LLM_CALLS = 50;
export const DEFAULT_RLM_MAX_OUTPUT_CHARS = 10_000;
export const DEFAULT_RLM_TIMEOUT_SUMMARY_MS = 10_000;
export const MAX_RLM_REPL_OUTPUT_CHARS = 40_000;
